import Head from "next/head";
import Image from "next/image";
import Link from "next/dist/client/link";
import css from "../styles/Home.module.css";

import hiroko from "../public/assets/hiro.jpg";

export default function Home() {
    return (
        <div className={css.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className={css.mainContainer}>
                    <div className={css.mainLeftPart}>
                        <Image
                            src={hiroko}
                            width={500}
                            height={500}
                            
                            alt="image profil Hiroko"
                        />
                    </div>

                    <div className={css.mainRightPart}>
                    
                        <h2>Konnichiwa !</h2>
                        <h2>こんにちは !</h2>
                        <div>

                        <h3>Venez apprendre le japonais dans une ambiance conviviale autour d&apos;un café !</h3>
                        <p>
                            Je vous propose d&apos;apprendre la langue japonaise par petits groupes dans le cadre d&apos;un méthode ludique mettant en avant la pratique par la conversation. Avec mon expérience de plus de 20 ans en tant que professeur, vous êtes certains de progresser efficacement. 
                        </p>
                        </div>

                        
                        {/* <div className={css.liens}>
                            <Link href="/Horaire">
                                <a className={css.a1}>Horaire</a>
                            </Link>
                            <Link href="/Galerie">
                                <a className={css.a2}>Galerie</a>
                            </Link>
                            <Link href="/Contact">
                                <a className={css.a3}>Contact</a>
                            </Link>
                        </div> */}
                    </div>
                </div>
            </main>
        </div>
    );
}
